### ISSUE TITLE
Wrong speed data in GPX

### ISSUE THREAD

**Issue by Johan-de-Wit** [JuanIrache/gopro-utils#16]
It seems that the speed data produced with V3.22 of gopro2gpx.exe is not correct. In the GPX file te speed tag is empty for a few wrong values. At least that is the result I got when trying to get the data out of a Gopro Hero 7 mp4 file. 
I'm not experienced, could someone take a  look?

**Comment by JuanIrache** [comment]
Can you send me a sample to juan at tailorandwayne dot com?

**Comment by Johan-de-Wit** [comment]
Send you a direct mail

**Comment by JuanIrache** [comment]
As discussed by email this is not really an issue. Gpx files do not include speed at all. Thanks
