### ISSUE TITLE
Accelerometer data starts from 1000ms and ends for about 2 seconds before video ends

### ISSUE THREAD

**Issue by Hamulus** [JuanIrache/gopro-utils#17]
The first record in accelerometer CSV is always at 1000ms. Also last 2 seconds of data are lost from the end of video. For example is a vido has 25seconds length, the last data record is for 23th second

**Comment by JuanIrache** [comment]
Hi, What camera are you using? Could you send me a sample (maybe privately?) juan at tailorandwayne dot com. I've experienced that sort of behaviour on the Hero5 Session, but since there is no GPS timestamp it's hard to match the timecode with the accelerometer/gyroscope data exactly.

**Comment by Hamulus** [comment]
the sample can be downloaded here
http://ragra.ru/video/GX011149.zip
the accelerometer data is attached to this comment
I am using GoPro Hero Black 7
[GX011149-accl.zip](https://github.com/JuanIrache/gopro-utils/files/3041685/GX011149-accl.zip)

**Comment by JuanIrache** [comment]
Thanks. If you were using the precompiled GPMD2CSV please update it, I had forgotten to push the latest update regarding milliseconds there. You might also want to use the new drag and drop tool: https://tailorandwayne.com/gopro-telemetry-extractor/

Regarding the last seconds, that might still be an issue, I'm not sure the sensor recordings always covers the entire video.

**Comment by Hamulus** [comment]
yes, the latest version has no 1000ms bug, thanks

but the last two seconds (even 2.5 seconds) are still not in the csv
I tried videos with different durations: there are always 2.5 seconds dropped

but I also tried the online tool: it differs with the windows compiled version
I used it for the same file and I got the same number of accelerometer values records with the same values, but timestamps are different: the last timestamp for windows tool is  14029.9494949495 but the last timestamp from online tool is 13994.949494949495
but they both contain the same values

**Comment by JuanIrache** [comment]
Ok, will have a look at it when I get some spare time.

**Comment by JuanIrache** [comment]
Timestamp differences fixed in 26e3e5f.

The missing 2.5 seconds will require more research.

**Comment by JuanIrache** [comment]
The duration problem appears to be related to how the camera records the data, not to these tools: https://github.com/gopro/gpmf-parser/issues/51
