### ISSUE TITLE
GoPro Hero 7 black gives 20Hz GPS timestamps

### ISSUE THREAD

**Issue by RobertdeLeeuw-IHomer** [JuanIrache/gopro-utils#18]
I have used your tools, love them. GoPro hero 7 gives 20 GPS fixes per second, your readme says 1Hz. Maybe that has changed with newer versions.
But the software I use for GPX files, does not like this. It only works with 1Hz files. It cannot process the microseconds, so it gives a division by zero exception when calculating speeds.

**Comment by JuanIrache** [comment]
Yes, I think the 1Hz figure has always been wrong. It came from the original repo.

What software are you using? You can try selecting the Virb export option form the online tool, it simplifies the data to 1Hz: https://tailorandwayne.com/gopro-telemetry-extractor/

Let me know how that goes.

**Comment by RobertdeLeeuw-IHomer** [comment]
Is that Virb export option not available in the commandline version? Uploading a couple of 8Gb GoPro files to your servers takes a while and uses a lot of your data.

**Comment by JuanIrache** [comment]
No, the simplification to 1Hz is done in JavaScript, so it's not related to this repo or the command line version. However, note that your video is never uploaded to the server. The metadata is extracted in your browser and only a small packet (about 1.5mb) is transferred for the final formatting. I might have to make that more clear in the website.
