### ISSUE TITLE
Invalid GPS coordinates on GoPro 6

### ISSUE THREAD

**Issue by highsource** [JuanIrache/gopro-utils#2]
I am trying to export a GPX track from an MP4 video filmed on GoPro 6.

Somehow I'm getting invalid coordinates. I see several problems which appear on the exported GPX track - but which I don't see on the GPS gauge in Quik.
I will create a separate issue per problem.

First problem is that I'm getting completely off-the track coordinates. Here's a example:

![qgis-3](https://user-images.githubusercontent.com/6707996/46581211-fefe7800-ca34-11e8-97c6-dcb651bc6571.PNG)

The video is filmed in Germany (around 8.663, 50.232). A few first points on the exported GPX track lie north of Canada (-128.4998971, 80.8641778). Also the elevation for these points is exported as `20841.167` (in reality should be around `202`).

Quik seem to show this track correctly:

![quik](https://user-images.githubusercontent.com/6707996/46581213-06258600-ca35-11e8-96c2-028c4f2959a7.PNG)

The complete video is ca. 3.4GB so I can't reasonably share it. I also don't know how can I cut it while keeping all the streams including `GoPro MET`.

Below is the `.bin` file I've exported from the video:

[GX030039.bin.zip](https://github.com/JuanIrache/gopro-utils/files/2453855/GX030039.bin.zip)

This is how I've exported it:

```
ffmpeg -y -i GX030039.MP4 -codec copy -map 0:3:handler_name:" GoPro MET" -f rawvideo  GX030039.bin
```

Below is the (zipped due to GitHub) GPX track:

[GX030039.gpx.zip](https://github.com/JuanIrache/gopro-utils/files/2453856/GX030039.gpx.zip)

Exported using:

```
gopro2gpx -i GX030039.bin -o GX030039.gpx
```

Invalid points look like:

```xml
			<trkpt lat="80.8641778" lon="-128.4998971">
				<ele>20841.167</ele>
				<time>2018-09-29T10:20:53Z</time>
			</trkpt>
			<trkpt lat="80.8641778" lon="-128.4998971">
				<ele>20841.167</ele>
				<time>2018-09-29T10:20:54Z</time>
			</trkpt>
```

First valid point:

```xml
			<trkpt lat="50.2319754" lon="8.6630605">
				<ele>202.121</ele>
				<time>2018-09-29T10:23:51Z</time>
			</trkpt>
```

**Comment by JuanIrache** [comment]
Hi @highsource ,

I think the main problem is that these tools are meant to extract the data, not interpret it. The wrong GPS data might be in the video files (while the GPS antenna is finding satellites maybe?), but Quick understands that those locations are wrong and discards them. These tools do not interpret the data, so the points are left there.

I'm not sure this answer helps, but I think that's what you're seeing. Does that make sense?

**Comment by highsource** [comment]
Thank you for the response.

I understand the "it's just a data extraction tool" position. Unfortunately, I have no idea where to move from here. `gopro2gpx` produces invalid GPX track and there does not seem to be any other tool to export GPS data from GoPro videos available. At least I could not find one.

Normally, I'd also blame GPS precision. But a differen hemisphere? And an elevation of 20k? Does not look like a GPS problem for me. I'd check if maybe some other data is interpreted as GPS.

**Comment by JuanIrache** [comment]
I will look into it when I get a chance, but for now work is more urgent, sorry. If I were you I'd look for a GPX visual editor or something like that, where you can delete or neutralise points. Not sure if that exists, but it might. Have you tried exporting the data with RaceRender or Dashware to see if the problems are still there?

**Comment by JuanIrache** [comment]
I just realised I could use the GPS Accuracy data to try and filter the bad data. The JSON and CSV files will still containg the wrong data along with the accuracy data, but KML and GPX files should be much much cleaner now. I set the threshold arbitrarily, so let me know if it's too aggressive. Hope it helps.

**Comment by highsource** [comment]
Thank you very much for this implementation. That made one of the tracks look somewhat better. However,  GX10039 from #3 still looks pretty broken:

![image](https://user-images.githubusercontent.com/6707996/46621043-b32bfb80-cb26-11e8-9348-572bf230d137.png)
