### ISSUE TITLE
Could not find label in list

### ISSUE THREAD

**Issue by ghost** [JuanIrache/gopro-utils#22]
I was following the instruction in this article https://lucaselbert.medium.com/extracting-gopro-gps-and-other-telemetry-data-fadf97ed1834. However, when I ran the last step on windows:

gpmd2csv -i 115FA515-DF1E-498D-8B5B-3EAD29D8184B_1080p.bin -o 115FA515-DF1E-498D-8B5B-3EAD29D8184B_1080p.csv

It complained that 

Could not find label in list:   � (000002af)
Could not find label in list: :X�k (3a58e66b)
Could not find label in list: �pЃ (cc70d083)
Could not find label in list: �H� (ae489e0c)
Could not find label in list: �S�� (da5380d8)
Could not find label in list: �F� (dd460381)

Eventually, all csv files does not have any data. 

Could you please let me know why?

Thank you very much.

**Comment by JuanIrache** [comment]
What camera is that happening with?

In the past adding the labels to the reader fixed that kind of problem (they will just be ignored)

https://github.com/JuanIrache/gopro-utils/blob/master/telemetry/reader.go

**Comment by ghost** [comment]
It is  GoPro Hero 9

**Comment by ghost** [comment]
Even these labels are not in the list, the reader should still read gps data, correct? Why my csv file has not data?

**Comment by JuanIrache** [comment]
Yes. The GPS data should be unrelated to these labels. What do you see if you load your files here? https://goprotelemetryextractor.com/free/

Will see if my Hero9 on the latest firmware does this.

**Comment by ghost** [comment]
It said: Telemetry not found. Is this an original GoPro video file?

**Comment by JuanIrache** [comment]
> It said: Telemetry not found. Is this an original GoPro video file?

Is it? If you transferred the file with GoPro Quik or other tools, the file could be a compressed copy of the original. The safest way to reach the original video file is to copy it from the SD card
