### ISSUE TITLE
Obtain accurate frames timestamps to relate to other meta-data (gyro, GPS, etc)?

### ISSUE THREAD

**Issue by noamholz** [JuanIrache/gopro-utils#24]
Thanks for this helpful project!
Is there a way I can find the closest gyro value for each video frame?

**Comment by JuanIrache** [comment]
Hi,

I haven't used this in a long time, I'm not sure how I was dealing with that. Sorry.

**Comment by noamholz** [comment]
Hi, okay,  thanks for your quick reply!
